In [2]:
# !pip install beautifulsoup4

In [ ]:
# !pip install requests

In [ ]:
# !pip install lxml

In [1]:
url = 'https://www.worldometers.info/coronavirus/'

In [3]:
import requests

In [18]:
html = requests.get(url).text

In [19]:
type(html)

str

In [20]:
from bs4 import BeautifulSoup

In [21]:
soup = BeautifulSoup(html, 'html.parser')

In [22]:
tbody = soup.find('tbody')

In [24]:
tr = tbody.find_all('tr')

In [35]:
tr[8]

<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">100,962,518</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+23,950</td>
<td style="font-weight: bold; text-align:right;">1,107,791                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+245</td>
<td style="font-weight: bold; text-align:right">98,364,274</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+43,720</td>
<td style="text-align:right;font-weight:bold;">1,490,453</td>
<td style="font-weight: bold; text-align:right">3,531</td>
<td style="font-weight: bold; text-align:right">301,556</td>
<td style="font-weight: bold; text-align:right">3,309</td>
<td style="font-weight: bold; text-align:right">1,143,194,153</td>
<td style="font-weight: bold; text-align:right">3,414,505</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,805,269</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>302</td><td>0</td>
<td style="font-weight: bold; text-align:right">72</td>
<td style="font-weight: bold; text-align:right">0.7</td>
<td style="font-weight: bold; text-align:right">4,452</td>
</tr>

In [32]:
for item in range(8, len(tr)):
    print(tr[item])

<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">100,962,518</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+23,950</td>
<td style="font-weight: bold; text-align:right;">1,107,791                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+245</td>
<td style="font-weight: bold; text-align:right">98,364,274</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+43,720</td>
<td style="text-align:right;font-weight:bold;">1,490,453</td>
<td style="font-weight: bold; text-align:right">3,531</td>
<td style="font-weight: bold; text-align:right">301,556</td>
<td style="font-weight: bold; text-align:right">3,309</td>
<td style="font-weight: bold; text-align:right">1,143,194,153</td>
<td style="font-weight: bold; text-align:right">3,414,505</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,805,269</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>302</td><td>0</td>
<td style="font-weight: bold; text-align:right">72</td>
<td style="font-weight: bold; text-align:right">0.7</td>
<td style="font-weight: bold; text-align:right">4,452</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
<td style="font-weight: bold; text-align:right">44,674,874</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">530,633                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">44,138,805</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">5,436</td>
<td style="font-weight: bold; text-align:right">698</td>
<td style="font-weight: bold; text-align:right">31,760</td>
<td style="font-weight: bold; text-align:right">377</td>
<td style="font-weight: bold; text-align:right">907,369,299</td>
<td style="font-weight: bold; text-align:right">645,065</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,406,631,776</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>31</td><td>2,651</td><td>2</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">4</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
<td style="font-weight: bold; text-align:right">38,184,081</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+105,516</td>
<td style="font-weight: bold; text-align:right;">159,362                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+117</td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">37,057,794</span></td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+34,774</td>
<td style="text-align:right;font-weight:bold;">966,925</td>
<td style="font-weight: bold; text-align:right">869</td>
<td style="font-weight: bold; text-align:right">582,212</td>
<td style="font-weight: bold; text-align:right">2,430</td>
<td style="font-weight: bold; text-align:right">271,490,188</td>
<td style="font-weight: bold; text-align:right">4,139,547</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,584,518</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>412</td><td>0</td>
<td style="font-weight: bold; text-align:right">1,609</td>
<td style="font-weight: bold; text-align:right">2</td>
<td style="font-weight: bold; text-align:right">14,743</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
<td style="font-weight: bold; text-align:right">36,604,648</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">158,386                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">35,953,400</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+40,400</td>
<td style="text-align:right;font-weight:bold;">492,862</td>
<td style="font-weight: bold; text-align:right">1,406</td>
<td style="font-weight: bold; text-align:right">436,374</td>
<td style="font-weight: bold; text-align:right">1,888</td>
<td style="font-weight: bold; text-align:right">122,332,384</td>
<td style="font-weight: bold; text-align:right">1,458,359</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,883,596</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>530</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">5,876</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
<td style="font-weight: bold; text-align:right">35,482,252</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+46,221</td>
<td style="font-weight: bold; text-align:right;">690,465                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+167</td>
<td style="font-weight: bold; text-align:right">34,262,104</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">529,683</td>
<td style="font-weight: bold; text-align:right">8,318</td>
<td style="font-weight: bold; text-align:right">164,763</td>
<td style="font-weight: bold; text-align:right">3,206</td>
<td style="font-weight: bold; text-align:right">63,776,166</td>
<td style="font-weight: bold; text-align:right">296,146</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,353,593</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<!-- 1 Case/Death/Test every X -->
<td>6</td><td>312</td><td>3</td>
<td style="font-weight: bold; text-align:right">215</td>
<td style="font-weight: bold; text-align:right">0.8</td>
<td style="font-weight: bold; text-align:right">2,460</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>
<td style="font-weight: bold; text-align:right">27,408,854</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+77,604</td>
<td style="font-weight: bold; text-align:right;">30,793                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+24</td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">26,431,550</span></td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+49,378</td>
<td style="text-align:right;font-weight:bold;">946,511</td>
<td style="font-weight: bold; text-align:right">443</td>
<td style="font-weight: bold; text-align:right">533,974</td>
<td style="font-weight: bold; text-align:right">600</td>
<td style="font-weight: bold; text-align:right">15,804,065</td>
<td style="font-weight: bold; text-align:right">307,892</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/south-korea-population/">51,329,899</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>1,667</td><td>3</td>
<td style="font-weight: bold; text-align:right">1,512</td>
<td style="font-weight: bold; text-align:right">0.5</td>
<td style="font-weight: bold; text-align:right">18,440</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/japan/">Japan</a></td>
<td style="font-weight: bold; text-align:right">25,405,350</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+137,193</td>
<td style="font-weight: bold; text-align:right;">50,608                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+147</td>
<td style="font-weight: bold; text-align:right">20,774,961</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+8,190</td>
<td style="text-align:right;font-weight:bold;">4,579,781</td>
<td style="font-weight: bold; text-align:right">361</td>
<td style="font-weight: bold; text-align:right">202,296</td>
<td style="font-weight: bold; text-align:right">403</td>
<td style="font-weight: bold; text-align:right">82,540,464</td>
<td style="font-weight: bold; text-align:right">657,249</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/japan-population/">125,584,838</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>5</td><td>2,482</td><td>2</td>
<td style="font-weight: bold; text-align:right">1,092</td>
<td style="font-weight: bold; text-align:right">1</td>
<td style="font-weight: bold; text-align:right">36,468</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
<td style="font-weight: bold; text-align:right">24,488,080</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">181,733                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">23,799,178</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">507,169</td>
<td style="font-weight: bold; text-align:right">320</td>
<td style="font-weight: bold; text-align:right">406,355</td>
<td style="font-weight: bold; text-align:right">3,016</td>
<td style="font-weight: bold; text-align:right">258,382,332</td>
<td style="font-weight: bold; text-align:right">4,287,595</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,262,770</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>332</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">8,416</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
<td style="font-weight: bold; text-align:right">24,024,746</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">197,253                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">23,758,420</span></td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+3,819</td>
<td style="text-align:right;font-weight:bold;">69,073</td>
<td style="font-weight: bold; text-align:right">146</td>
<td style="font-weight: bold; text-align:right">350,737</td>
<td style="font-weight: bold; text-align:right">2,880</td>
<td style="font-weight: bold; text-align:right">522,526,476</td>
<td style="font-weight: bold; text-align:right">7,628,357</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,497,907</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>347</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">1,008</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
<td style="font-weight: bold; text-align:right">21,628,829</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+5,561</td>
<td style="font-weight: bold; text-align:right;">392,342                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+59</td>
<td style="font-weight: bold; text-align:right">21,030,317</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+6,690</td>
<td style="text-align:right;font-weight:bold;">206,170</td>
<td style="font-weight: bold; text-align:right">2,300</td>
<td style="font-weight: bold; text-align:right">148,340</td>
<td style="font-weight: bold; text-align:right">2,691</td>
<td style="font-weight: bold; text-align:right">273,400,000</td>
<td style="font-weight: bold; text-align:right">1,875,095</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,805,947</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>7</td><td>372</td><td>1</td>
<td style="font-weight: bold; text-align:right">38</td>
<td style="font-weight: bold; text-align:right">0.4</td>
<td style="font-weight: bold; text-align:right">1,414</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/turkey/">Turkey</a></td>
<td style="font-weight: bold; text-align:right">17,005,537</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">101,400                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right;">N/A</td>
<td style="text-align:right;font-weight:bold;">N/A</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">198,751</td>
<td style="font-weight: bold; text-align:right">1,185</td>
<td style="font-weight: bold; text-align:right">162,743,369</td>
<td style="font-weight: bold; text-align:right">1,902,052</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/turkey-population/">85,561,976</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>5</td><td>844</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">1,385</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">12</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/spain/">Spain</a></td>
<td style="font-weight: bold; text-align:right">13,614,807</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">116,108                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">13,403,322</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">95,377</td>
<td style="font-weight: bold; text-align:right">339</td>
<td style="font-weight: bold; text-align:right">291,418</td>
<td style="font-weight: bold; text-align:right">2,485</td>
<td style="font-weight: bold; text-align:right">471,036,328</td>
<td style="font-weight: bold; text-align:right">10,082,298</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/spain-population/">46,719,142</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>402</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">2,041</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">13</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/viet-nam/">Vietnam</a></td>
<td style="font-weight: bold; text-align:right">11,518,511</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+362</td>
<td style="font-weight: bold; text-align:right;">43,178                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+1</td>
<td style="font-weight: bold; text-align:right">10,609,139</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+151</td>
<td style="text-align:right;font-weight:bold;">866,194</td>
<td style="font-weight: bold; text-align:right">72</td>
<td style="font-weight: bold; text-align:right">116,403</td>
<td style="font-weight: bold; text-align:right">436</td>
<td style="font-weight: bold; text-align:right">85,826,548</td>
<td style="font-weight: bold; text-align:right">867,342</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/viet-nam-population/">98,953,541</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>9</td><td>2,292</td><td>1</td>
<td style="font-weight: bold; text-align:right">4</td>
<td style="font-weight: bold; text-align:right">0.01</td>
<td style="font-weight: bold; text-align:right">8,754</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">14</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/australia/">Australia</a></td>
<td style="font-weight: bold; text-align:right">10,759,272</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+4,843</td>

In [41]:
# [[1,'usa', 55655, 5587], [2, 'inida', 554, 888]]

In [38]:
complete_data = []
for item in range(8, len(tr)):
    country_data = []
    table_row = tr[item]
    td = table_row.find_all('td') # one table row has multiple table data
    for item in td:
        country_data.append(item.text) # extract data of each country
        
    complete_data.append(country_data) # append all data of each country on a list

In [40]:
complete_data[0]

['1',
 'USA',
 '100,962,518',
 '+23,950',
 '1,107,791                                ',
 '+245',
 '98,364,274',
 '+43,720',
 '1,490,453',
 '3,531',
 '301,556',
 '3,309',
 '1,143,194,153',
 '3,414,505',
 '334,805,269 ',
 'North America',
 '3',
 '302',
 '0',
 '72',
 '0.7',
 '4,452']

In [47]:
clean_data = list(map(lambda x: x[1:10], complete_data ))

In [48]:
clean_data

[['USA',
  '100,962,518',
  '+23,950',
  '1,107,791                                ',
  '+245',
  '98,364,274',
  '+43,720',
  '1,490,453',
  '3,531'],
 ['India',
  '44,674,874',
  '',
  '530,633                                ',
  '',
  '44,138,805',
  '',
  '5,436',
  '698'],
 ['France',
  '38,184,081',
  '+105,516',
  '159,362                                ',
  '+117',
  '37,057,794',
  '+34,774',
  '966,925',
  '869'],
 ['Germany',
  '36,604,648',
  '',
  '158,386                                ',
  '',
  '35,953,400',
  '+40,400',
  '492,862',
  '1,406'],
 ['Brazil',
  '35,482,252',
  '+46,221',
  '690,465                                ',
  '+167',
  '34,262,104',
  '',
  '529,683',
  '8,318'],
 ['S. Korea',
  '27,408,854',
  '+77,604',
  '30,793                                ',
  '+24',
  '26,431,550',
  '+49,378',
  '946,511',
  '443'],
 ['Japan',
  '25,405,350',
  '+137,193',
  '50,608                                ',
  '+147',
  '20,774,961',
  '+8,190',
  '4,579,781',
  '361'],
 ['Italy',
  '24,488,080',
  '',
  '181,733                                ',
  '',
  '23,799,178',
  '',
  '507,169',
  '320'],
 ['UK',
  '24,024,746',
  '',
  '197,253                                ',
  '',
  '23,758,420',
  '+3,819',
  '69,073',
  '146'],
 ['Russia',
  '21,628,829',
  '+5,561',
  '392,342                                ',
  '+59',
  '21,030,317',
  '+6,690',
  '206,170',
  '2,300'],
 ['Turkey',
  '17,005,537',
  '',
  '101,400                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  ''],
 ['Spain',
  '13,614,807',
  '',
  '116,108                                ',
  '',
  '13,403,322',
  '',
  '95,377',
  '339'],
 ['Vietnam',
  '11,518,511',
  '+362',
  '43,178                                ',
  '+1',
  '10,609,139',
  '+151',
  '866,194',
  '72'],
 ['Australia',
  '10,759,272',
  '+4,843',
  '16,264                                ',
  '+20',
  '10,546,102',
  '',
  '196,906',
  '95'],
 ['Argentina',
  '9,739,856',
  '',
  '130,034                                ',
  '',
  '9,591,684',
  '+1,486',
  '18,138',
  '241'],
 ['Netherlands',
  '8,547,416',
  '+938',
  '22,926                                ',
  '+4',
  '8,500,610',
  '+1,801',
  '23,880',
  '43'],
 ['Taiwan',
  '8,395,477',
  '+16,034',
  '14,522                                ',
  '+22',
  '8,077,607',
  '+22,659',
  '303,348',
  ''],
 ['Iran',
  '7,559,958',
  '+34',
  '144,648                                ',
  '+3',
  '7,335,357',
  '+27',
  '79,953',
  '72'],
 ['Mexico',
  '7,145,409',
  '+12,617',
  '330,592                                ',
  '+67',
  '6,407,215',
  '+6,456',
  '407,602',
  '4,798'],
 ['Indonesia',
  '6,686,181',
  '+3,744',
  '160,071                                ',
  '+45',
  '6,478,450',
  '+4,179',
  '47,660',
  '2,771'],
 ['Poland',
  '6,355,424',
  '+913',
  '118,347                                ',
  '+7',
  '5,335,940',
  '',
  '901,137',
  '1,530'],
 ['Colombia',
  '6,318,021',
  '',
  '141,911                                ',
  '',
  '6,142,640',
  '',
  '33,470',
  '342'],
 ['Austria',
  '5,588,468',
  '+4,669',
  '21,242                                ',
  '+1',
  '5,521,209',
  '+3,308',
  '46,017',
  '47'],
 ['Portugal',
  '5,546,290',
  '',
  '25,517                                ',
  '',
  '5,501,942',
  '+1,173',
  '18,831',
  '61'],
 ['Greece',
  '5,404,690',
  '',
  '34,309                                ',
  '',
  '5,345,133',
  '+6,312',
  '25,248',
  '115'],
 ['Ukraine',
  '5,341,284',
  '',
  '110,586                                ',
  '',
  '5,217,903',
  '+1,045',
  '12,795',
  ''],
 ['Malaysia',
  '5,003,557',
  '+1,649',
  '36,732                                ',
  '+16',
  '4,945,067',
  '+1,675',
  '21,758',
  '101'],
 ['Chile',
  '4,941,227',
  '+1,923',
  '62,597                                ',
  '+10',
  '4,867,554',
  '',
  '11,076',
  '129'],
 ['DPRK',
  '4,772,813',
  '',
  '74                                ',
  '',
  '4,772,739',
  '',
  '0',
  ''],
 ['Israel',
  '4,730,502',
  '+888',
  '11,882                                ',
  '',
  '4,704,016',
  '',
  '14,604',
  '22'],
 ['Thailand',
  '4,711,528',
  '',
  '33,285                                ',
  '',
  '4,649,509',
  '',
  '28,734',
  '1,496'],
 ['Belgium',
  '4,644,478',
  '',
  '33,086                                ',
  '',
  '4,586,061',
  '+1,207',
  '25,331',
  '48'],
 ['Czechia',
  '4,562,887',
  '+1,516',
  '41,923                                ',
  '+5',
  '4,512,355',
  '+763',
  '8,609',
  '46'],
 ['Canada',
  '4,423,053',
  '',
  '48,044                                ',
  '',
  '4,311,883',
  '',
  '63,126',
  '99'],
 ['Switzerland',
  '4,317,035',
  '',
  '14,318                                ',
  '',
  '4,236,049',
  '+3,074',
  '66,668',
  '53'],
 ['Peru',
  '4,304,745',
  '',
  '217,519                                ',
  '',
  '3,985,733',
  '+6,177',
  '101,493',
  '111'],
 ['South Africa',
  '4,043,242',
  '+225',
  '102,464                                ',
  '',
  '3,912,506',
  '',
  '28,272',
  '192'],
 ['Philippines',
  '4,042,936',
  '+883',
  '64,770                                ',
  '+20',
  '3,960,685',
  '+1,160',
  '17,481',
  '162'],
 ['Romania',
  '3,298,738',
  '',
  '67,289                                ',
  '',
  '3,226,943',
  '',
  '4,506',
  '101'],
 ['Denmark',
  '3,150,954',
  '+771',
  '7,557                                ',
  '+2',
  '3,136,805',
  '+325',
  '6,592',
  '9'],
 ['Sweden',
  '2,632,091',
  '',
  '21,095                                ',
  '',
  '2,595,891',
  '+341',
  '15,105',
  '19'],
 ['Iraq',
  '2,464,375',
  '',
  '25,366                                ',
  '',
  '2,437,963',
  '',
  '1,046',
  '21'],
 ['Serbia',
  '2,426,848',
  '+672',
  '17,418                                ',
  '+6',
  '2,399,359',
  '+650',
  '10,071',
  '23'],
 ['Hong Kong',
  '2,177,436',
  '+9,952',
  '10,842                                ',
  '+16',
  '1,907,882',
  '+4,746',
  '258,712',
  '21'],
 ['Singapore',
  '2,174,989',
  '+1,817',
  '1,706                                ',
  '',
  '2,099,889',
  '+1,107',
  '73,394',
  '8'],
 ['Hungary',
  '2,166,352',
  '',
  '48,287                                ',
  '',
  '2,104,358',
  '',
  '13,707',
  '7'],
 ['Bangladesh',
  '2,036,685',
  '+22',
  '29,435                                ',
  '',
  '1,986,210',
  '+32',
  '21,040',
  '1,331'],
 ['New Zealand',
  '1,979,614',
  '',
  '3,337                                ',
  '',
  '1,942,897',
  '',
  '33,380',
  ''],
 ['Slovakia',
  '1,856,552',
  '+161',
  '20,745                                ',
  '+3',
  '1,834,387',
  '+91',
  '1,420',
  '23'],
 ['Georgia',
  '1,806,918',
  '',
  '16,882                                ',
  '',
  '1,776,548',
  '',
  '13,488',
  ''],
 ['Jordan',
  '1,746,997',
  '',
  '14,122                                ',
  '',
  '1,731,007',
  '',
  '1,868',
  '59'],
 ['Ireland',
  '1,680,548',
  '',
  '8,159                                ',
  '',
  '1,666,852',
  '',
  '5,537',
  '10'],
 ['Pakistan',
  '1,575,355',
  '+25',
  '30,632                                ',
  '',
  '1,538,689',
  '',
  '6,034',
  '34'],
 ['Norway',
  '1,469,983',
  '+205',
  '4,325                                ',
  '',
  '1,463,130',
  '+53',
  '2,528',
  '20'],
 ['Finland',
  '1,405,255',
  '',
  '7,448                                ',
  '',
  '1,370,790',
  '+1,791',
  '27,017',
  '21'],
 ['Kazakhstan',
  '1,397,667',
  '+140',
  '13,693                                ',
  '',
  '1,382,292',
  '',
  '1,682',
  '24'],
 ['Bulgaria',
  '1,288,196',
  '+208',
  '38,053                                ',
  '',
  '1,245,714',
  '+207',
  '4,429',
  '40'],
 ['Lithuania',
  '1,278,458',
  '+860',
  '9,439                                ',
  '+2',
  '1,262,876',
  '+273',
  '6,143',
  '8'],
 ['Morocco',
  '1,269,570',
  '+179',
  '16,286                                ',
  '+1',
  '1,252,212',
  '+186',
  '1,072',
  '293'],
 ['Slovenia',
  '1,266,751',
  '+2,669',
  '6,944                                ',
  '+1',
  '1,242,639',
  '+1,582',
  '17,168',
  '17'],
 ['Croatia',
  '1,255,155',
  '+298',
  '17,364                                ',
  '+8',
  '1,235,663',
  '+196',
  '2,128',
  '9'],
 ['Lebanon',
  '1,220,800',
  '',
  '10,740                                ',
  '',
  '1,087,587',
  '',
  '122,473',
  '74'],
 ['Guatemala',
  '1,161,983',
  '+1,620',
  '19,958                                ',
  '+1',
  '1,133,955',
  '+548',
  '8,070',
  '5'],
 ['Costa Rica',
  '1,148,914',
  '',
  '9,046                                ',
  '',
  '860,711',
  '',
  '279,157',
  '52'],
 ['Tunisia',
  '1,147,145',
  '+73',
  '29,269                                ',
  '+1',
  'N/A',
  'N/A',
  'N/A',
  '44'],
 ['Bolivia',
  '1,112,997',
  '+496',
  '22,251                                ',
  '+1',
  '1,078,596',
  '+133',
  '12,150',
  '220'],
 ['Cuba',
  '1,111,452',
  '+5',
  '8,530                                ',
  '',
  '1,102,815',
  '+12',
  '107',
  '23'],
 ['UAE',
  '1,044,934',
  '+91',
  '2,348                                ',
  '',
  '1,025,215',
  '+218',
  '17,371',
  ''],
 ['Ecuador',
  '1,011,132',
  '',
  '35,940                                ',
  '',
  '973,448',
  '',
  '1,744',
  '759'],
 ['Panama',
  '1,009,252',
  '',
  '8,533                                ',
  '',
  '991,093',
  '',
  '9,626',
  '16'],
 ['Nepal',
  '1,000,912',
  '+1',
  '12,019                                ',
  '',
  '988,814',
  '+14',
  '79',
  ''],
 ['Uruguay',
  '995,402',
  '',
  '7,541                                ',
  '',
  '986,371',
  '',
  '1,490',
  '18'],
 ['Belarus',
  '994,037',
  '',
  '7,118                                ',
  '',
  '985,592',
  '',
  '1,327',
  ''],
 ['Mongolia',
  '993,705',
  '+333',
  '2,179                                ',
  '',
  '988,552',
  '+1,411',
  '2,974',
  '192'],
 ['Latvia',
  '966,131',
  '+453',
  '6,105                                ',
  '+2',
  '950,319',
  '',
  '9,707',
  '3'],
 ['Saudi Arabia',
  '825,936',
  '+77',
  '9,476                                ',
  '+2',
  '813,405',
  '+48',
  '3,055',
  '27'],
 ['Azerbaijan',
  '824,574',
  '+62',
  '9,984                                ',
  '+1',
  '814,298',
  '+37',
  '292',
  ''],
 ['Paraguay',
  '777,525',
  '',
  '19,630                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '7'],
 ['Bahrain',
  '696,851',
  '',
  '1,536                                ',
  '',
  '694,364',
  '',
  '951',
  '2'],
 ['Sri Lanka',
  '671,719',
  '+5',
  '16,806                                ',
  '+1',
  '654,892',
  '+3',
  '21',
  ''],
 ['Kuwait',
  '662,747',
  '',
  '2,570                                ',
  '',
  '660,095',
  '',
  '82',
  ''],
 ['Dominican Republic',
  '650,990',
  '',
  '4,384                                ',
  '',
  '644,785',
  '',
  '1,821',
  '4'],
 ['Myanmar',
  '633,341',
  '+17',
  '19,488                                ',
  '',
  '607,877',
  '+14',
  '5,976',
  ''],
 ['Palestine',
  '620,816',
  '',
  '5,404                                ',
  '',
  '614,962',
  '',
  '450',
  '17'],
 ['Cyprus',
  '618,248',
  '',
  '1,237                                ',
  '',
  '605,050',
  '',
  '11,961',
  '60'],
 ['Estonia',
  '609,769',
  '+536',
  '2,799                                ',
  '+9',
  '524,990',
  '',
  '81,980',
  '5'],
 ['Moldova',
  '595,402',
  '+329',
  '11,920                                ',
  '+2',
  '504,142',
  '',
  '79,340',
  '49'],
 ['Venezuela',
  '547,891',
  '',
  '5,829                                ',
  '',
  '540,991',
  '',
  '1,071',
  '36'],
 ['Egypt',
  '515,645',
  '',
  '24,613                                ',
  '',
  '442,182',
  '',
  '48,850',
  '122'],
 ['Libya',
  '507,100',
  '',
  '6,437                                ',
  '',
  '500,610',
  '',
  '53',
  ''],
 ['Ethiopia',
  '494,857',
  '+71',
  '7,572                                ',
  '',
  '472,547',
  '+25',
  '14,738',
  '1'],
 ['Qatar',
  '481,904',
  '+608',
  '685                                ',
  '',
  '478,981',
  '+459',
  '2,238',
  ''],
 ['Réunion',
  '477,305',
  '',
  '903                                ',
  '',
  '418,572',
  '',
  '57,830',
  '10'],
 ['Honduras',
  '458,921',
  '',
  '11,051                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '105'],
 ['Armenia',
  '445,828',
  '',
  '8,712                                ',
  '',
  '434,979',
  '',
  '2,137',
  ''],
 ['Bosnia and Herzegovina',
  '400,613',
  '+12',
  '16,207                                ',
  '+2',
  '378,468',
  '+8',
  '5,938',
  ''],
 ['Oman',
  '399,119',
  '',
  '4,260                                ',
  '',
  '384,669',
  '',
  '10,190',
  '2'],
 ['North Macedonia',
  '345,067',
  '',
  '9,591                                ',
  '',
  '335,261',
  '',
  '215',
  ''],
 ['Kenya',
  '341,977',
  '+44',
  '5,684                                ',
  '',
  '335,740',
  '+42',
  '553',
  '1'],
 ['Zambia',
  '333,746',
  '',
  '4,019                                ',
  '',
  '329,690',
  '',
  '37',
  ''],
 ['Albania',
  '333,455',
  '+42',
  '3,593                                ',
  '',
  '328,263',
  '+11',
  '1,599',
  ''],
 ['Botswana',
  '326,800',
  '+167',
  '2,793                                ',
  '+3',
  '323,747',
  '',
  '260',
  '1'],
 ['Luxembourg',
  '297,757',
  '',
  '1,133                                ',
  '',
  '288,991',
  '',
  '7,633',
  ''],
 ['Montenegro',
  '283,895',
  '+51',
  '2,790                                ',
  '',
  '280,846',
  '+36',
  '259',
  '6'],
 ['Algeria',
  '271,122',
  '+9',
  '6,881                                ',
  '',
  '182,586',
  '+4',
  '81,655',
  ''],
 ['Nigeria',
  '266,283',
  '',
  '3,155                                ',
  '',
  '259,640',
  '',
  '3,488',
  '11'],
 ['Zimbabwe',
  '259,356',
  '+192',
  '5,622                                ',
  '+2',
  '253,061',
  '+206',
  '673',
  '12'],
 ['Uzbekistan',
  '247,424',
  '+120',
  '1,637                                ',
  '',
  '241,486',
  '',
  '4,301',
  '23'],
 ['Brunei ',
  '241,044',
  '',
  '225                                ',
  '',
  '222,140',
  '',
  '18,679',
  '3'],
 ['Mozambique',
  '230,624',
  '',
  '2,226                                ',
  '',
  '228,310',
  '',
  '88',
  '11'],
 ['Martinique',
  '224,468',
  '',
  '1,071                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '8'],
 ['Laos',
  '216,919',
  '+76',
  '758                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  ''],
 ['Iceland',
  '207,504',
  '+149',
  '219                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '2'],
 ['Kyrgyzstan',
  '206,543',
  '',
  '2,991                                ',
  '',
  '196,406',
  '',
  '7,146',
  '131'],
 ['Afghanistan',
  '206,331',
  '+38',
  '7,835                                ',
  '',
  '184,079',
  '+32',
  '14,417',
  '1,124'],
 ['El Salvador',
  '201,785',
  '',
  '4,230                                ',
  '',
  '179,410',
  '',
  '18,145',
  '8'],
 ['Guadeloupe',
  '197,918',
  '',
  '995                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '19'],
 ['Maldives',
  '185,632',
  '',
  '311                                ',
  '',
  '163,687',
  '',
  '21,634',
  '25'],
 ['Trinidad and Tobago',
  '185,528',
  '+151',
  '4,268                                ',
  '+1',
  '181,075',
  '+163',
  '185',
  '8'],
 ['Ghana',
  '171,023',
  '',
  '1,461                                ',
  '',
  '169,553',
  '',
  '9',
  '2'],
 ['Namibia',
  '169,946',
  '',
  '4,080                                ',
  '',
  '165,826',
  '',
  '40',
  ''],
 ['Uganda',
  '169,810',
  '',
  '3,630                                ',
  '',
  '100,431',
  '',
  '65,749',
  '3'],
 ['Jamaica',
  '152,517',
  '',
  '3,399                                ',
  '',
  '99,392',
  '',
  '49,726',
  ''],
 ['Cambodia',
  '138,176',
  '+19',
  '3,056                                ',
  '',
  '135,035',
  '+8',
  '85',
  ''],
 ['Rwanda',
  '132,811',
  '+49',
  '1,467                                ',
  '',
  '131,112',
  '',
  '232',
  ''],
 ['Cameroon',
  '123,993',
  '',
  '1,965                                ',
  '',
  '118,616',
  '',
  '3,412',
  '13'],
 ['Malta',
  '115,907',
  '+16',
  '809                                ',
  '',
  '114,518',
  '+19',
  '580',
  '4'],
 ['Angola',
  '104,750',
  '',
  '1,925                                ',
  '',
  '102,538',
  '',
  '287',
  ''],
 ['Barbados',
  '104,416',
  '',
  '567                                ',
  '',
  '102,435',
  '',
  '1,414',
  ''],
 ['French Guiana',
  '96,389',
  '',
  '411                                ',
  '',
  '11,254',
  '',
  '84,724',
  '2'],
 ['Channel Islands',
  '96,208',
  '+180',
  '208                                ',
  '+1',
  '95,434',
  '+130',
  '566',
  ''],
 ['DRC',
  '94,452',
  '',
  '1,456                                ',
  '',
  '83,728',
  '',
  '9,268',
  ''],
 ['Senegal',
  '88,887',
  '+14',
  '1,968                                ',
  '',
  '86,887',
  '+15',
  '32',
  ''],
 ['Malawi',
  '88,086',
  '',
  '2,685                                ',
  '',
  '85,009',
  '',
  '392',
  '67'],
 ['Ivory Coast',
  '87,890',
  '+1',
  '830                                ',
  '',
  '87,053',
  '+2',
  '7',
  ''],
 ['Suriname',
  '81,581',
  '',
  '1,393                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  ''],
 ['French Polynesia',
  '77,275',
  '',
  '649                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '7'],
 ['New Caledonia',
  '77,127',
  '+1,032',
  '314                                ',
  '',
  '75,257',
  '+654',
  '1,556',
  '9'],
 ['Eswatini',
  '73,908',
  '',
  '1,422                                ',
  '',
  '72,392',
  '',
  '94',
  ''],
 ['Guyana',
  '71,679',
  '+29',
  '1,285                                ',
  '',
  '70,233',
  '+1',
  '161',
  ''],
 ['Belize',
  '69,117',
  '',
  '688                                ',
  '',
  '68,379',
  '',
  '50',
  '6'],
 ['Fiji',
  '68,451',
  '',
  '878                                ',
  '',
  '66,524',
  '',
  '1,049',
  ''],
 ['Madagascar',
  '67,488',
  '',
  '1,413                                ',
  '',
  '65,602',
  '',
  '473',
  ''],
 ['Sudan',
  '63,655',
  '',
  '4,991                                ',
  '',
  '58,083',
  '',
  '581',
  ''],
 ['Mauritania',
  '63,421',
  '',
  '997                                ',
  '',
  '62,421',
  '',
  '3',
  ''],
 ['Cabo Verde',
  '63,095',
  '+10',
  '412                                ',
  '',
  '62,563',
  '+33',
  '120',
  '23'],
 ['Bhutan',
  '62,512',
  '',
  '21                                ',
  '',
  '61,564',
  '',
  '927',
  ''],
 ['Syria',
  '57,409',
  '+2',
  '3,163                                ',
  '',
  '54,239',
  '+2',
  '7',
  ''],
 ['Burundi',
  '51,018',
  '',
  '38                                ',
  '',
  '50,638',
  '',
  '342',
  ''],
 ['Seychelles',
  '50,068',
  '',
  '171                                ',
  '',
  '49,606',
  '',
  '291',
  ''],
 ['Gabon',
  '48,973',
  '',
  '306                                ',
  '',
  '48,582',
  '',
  '85',
  ''],
 ['Andorra',
  '47,219',
  '',
  '157                                ',
  '',
  '46,731',
  '',
  '331',
  '14'],
 ['Papua New Guinea',
  '46,247',
  '',
  '668                                ',
  '',
  '43,982',
  '',
  '1,597',
  '7'],
 ['Curaçao',
  '45,986',
  '',
  '295                                ',
  '',
  '44,720',
  '',
  '971',
  '3'],
 ['Aruba',
  '43,641',
  '',
  '236                                ',
  '',
  '42,438',
  '',
  '967',
  '2'],
 ['Mayotte',
  '41,679',
  '',
  '187                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  ''],
 ['Mauritius',
  '41,175',
  '',
  '1,035                                ',
  '',
  '39,396',
  '',
  '744',
  ''],
 ['Tanzania',
  '40,806',
  '+150',
  '845                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '7'],
 ['Togo',
  '39,332',
  '',
  '290                                ',
  '',
  '39,035',

In [42]:
# ! pip install pandas
# ! pip install matplotlib
# ! pip install seaborn

In [43]:
import pandas as pd # as pd is alias name convention

In [49]:
df = pd.DataFrame(clean_data)

In [50]:
df

,0,1,2,3,4,5,6,7,8
0,USA,"100,962,518","+23,950","1,107,791",+245,"98,364,274","+43,720","1,490,453","3,531"
1,India,"44,674,874",,"530,633",,"44,138,805",,"5,436",698
2,France,"38,184,081","+105,516","159,362",+117,"37,057,794","+34,774","966,925",869
3,Germany,"36,604,648",,"158,386",,"35,953,400","+40,400","492,862","1,406"
4,Brazil,"35,482,252","+46,221","690,465",+167,"34,262,104",,"529,683","8,318"
...,...,...,...,...,...,...,...,...,...
225,Niue,180,+8,,,114,+3,66,
226,Vatican City,29,,,,29,,0,
227,Western Sahara,10,,1,,9,,0,
228,MS Zaandam,9,,2,,7,,0,
229,China,"345,529","+5,046","5,235",,"297,813","+3,198","42,481",128

In [51]:
col_names = ['country',
             'total cases',
             'new cases', 
             'total death',
             'new death', 
             'total recovered',
            'new recovered', 
            'active cases', 
            'critital']

In [52]:
# updating column name on pandas dataframe

In [53]:
df.columns = col_names # update column name of a dataframe

In [54]:
df.head() # print 5 data rows from top

,country,total cases,new cases,total death,new death,total recovered,new recovered,active cases,critital
0,USA,"100,962,518","+23,950","1,107,791",+245,"98,364,274","+43,720","1,490,453","3,531"
1,India,"44,674,874",,"530,633",,"44,138,805",,"5,436",698
2,France,"38,184,081","+105,516","159,362",+117,"37,057,794","+34,774","966,925",869
3,Germany,"36,604,648",,"158,386",,"35,953,400","+40,400","492,862","1,406"
4,Brazil,"35,482,252","+46,221","690,465",+167,"34,262,104",,"529,683","8,318"

In [55]:
df.tail() # last 5 data

,country,total cases,new cases,total death,new death,total recovered,new recovered,active cases,critital
225,Niue,180,+8,,,114,+3,66,
226,Vatican City,29,,,,29,,0,
227,Western Sahara,10,,1,,9,,0,
228,MS Zaandam,9,,2,,7,,0,
229,China,"345,529","+5,046","5,235",,"297,813","+3,198","42,481",128

# convert dataframe to csv

In [56]:
df.to_csv('covid-live_dec7.csv', index = False) # index = False -- dont save index

# Reading csv file in pandas

In [58]:
filename = 'covid-live_dec7.csv'
covid_data = pd.read_csv(filename)

In [59]:
covid_data.head()

,country,total cases,new cases,total death,new death,total recovered,new recovered,active cases,critital
0,USA,"100,962,518","+23,950","1,107,791",245.0,"98,364,274","+43,720","1,490,453","3,531"
1,India,"44,674,874",NaN,"530,633",NaN,"44,138,805",NaN,"5,436",698
2,France,"38,184,081","+105,516","159,362",117.0,"37,057,794","+34,774","966,925",869
3,Germany,"36,604,648",NaN,"158,386",NaN,"35,953,400","+40,400","492,862","1,406"
4,Brazil,"35,482,252","+46,221","690,465",167.0,"34,262,104",NaN,"529,683","8,318"

In [60]:
# NaN is a missing data

# Find no of missing value in each column

In [61]:
covid_data.isna()

,country,total cases,new cases,total death,new death,total recovered,new recovered,active cases,critital
0,False,False,False,False,False,False,False,False,False
1,False,False,True,False,True,False,True,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,True,False,True,False,False,False,False
4,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...
225,False,False,False,False,True,False,False,False,True
226,False,False,True,False,True,False,True,False,True
227,False,False,True,False,True,False,True,False,True
228,False,False,True,False,True,False,True,False,True
229,False,False,False,False,True,False,False,False,False

In [63]:
missing = covid_data.isna().sum()

In [64]:
missing

country              0
total cases          0
new cases          145
total death          0
new death          188
total recovered     20
new recovered      154
active cases        19
critital            91
dtype: int64