In [1]:
# 'https://www.worldometers.info/coronavirus/'

In [2]:
# !pip install beautifulsoup4

In [3]:
# !pip install requests

In [4]:
# !pip install lxml

In [5]:
url = 'https://www.worldometers.info/coronavirus/'

In [6]:
import requests

In [7]:
html = requests.get(url).text

In [8]:
type(html)

str

In [9]:
from bs4 import BeautifulSoup

In [10]:
soup = BeautifulSoup(html, 'html.parser')

In [11]:
tbody = soup.find('tbody')

In [12]:
tr = tbody.find_all('tr')

In [13]:
tr[0]

<tr class="total_row_world row_continent" data-continent="North America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>North America</nobr>
</td>
<td>119,599,532</td>
<td></td>
<td>1,567,145</td>
<td></td>
<td>114,916,459</td>
<td>+2,449</td>
<td>3,115,928</td>
<td>8,678</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="North America" style="display:none;">North America</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>

In [14]:
tr[1]

<tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Asia</nobr>
</td>
<td>200,478,586</td>
<td>+79,220</td>
<td>1,500,434</td>
<td>+56</td>
<td>191,046,405</td>
<td>+54,308</td>
<td>7,931,747</td>
<td>9,526</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Asia" style="display:none;">Asia</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>

In [15]:
tr[8]

<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">100,962,660</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">1,107,794                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">98,374,922</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">1,479,944</td>
<td style="font-weight: bold; text-align:right">3,495</td>
<td style="font-weight: bold; text-align:right">301,556</td>
<td style="font-weight: bold; text-align:right">3,309</td>
<td style="font-weight: bold; text-align:right">1,143,194,153</td>
<td style="font-weight: bold; text-align:right">3,414,505</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,805,269</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>302</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">4,420</td>
</tr>

In [16]:
for item in range(8, len(tr)):
    print(tr[item])

<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">100,962,660</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">1,107,794                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">98,374,922</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">1,479,944</td>
<td style="font-weight: bold; text-align:right">3,495</td>
<td style="font-weight: bold; text-align:right">301,556</td>
<td style="font-weight: bold; text-align:right">3,309</td>
<td style="font-weight: bold; text-align:right">1,143,194,153</td>
<td style="font-weight: bold; text-align:right">3,414,505</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,805,269</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>302</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">4,420</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
<td style="font-weight: bold; text-align:right">44,674,874</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">530,633                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">44,138,805</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">5,436</td>
<td style="font-weight: bold; text-align:right">698</td>
<td style="font-weight: bold; text-align:right">31,760</td>
<td style="font-weight: bold; text-align:right">377</td>
<td style="font-weight: bold; text-align:right">907,369,299</td>
<td style="font-weight: bold; text-align:right">645,065</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,406,631,776</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>31</td><td>2,651</td><td>2</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">4</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
<td style="font-weight: bold; text-align:right">38,184,081</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">159,362                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">37,057,677</span></td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">967,042</td>
<td style="font-weight: bold; text-align:right">869</td>
<td style="font-weight: bold; text-align:right">582,212</td>
<td style="font-weight: bold; text-align:right">2,430</td>
<td style="font-weight: bold; text-align:right">271,490,188</td>
<td style="font-weight: bold; text-align:right">4,139,547</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,584,518</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>412</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">14,745</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
<td style="font-weight: bold; text-align:right">36,649,979</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">158,559                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">35,986,500</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+33,100</td>
<td style="text-align:right;font-weight:bold;">504,920</td>
<td style="font-weight: bold; text-align:right">1,406</td>
<td style="font-weight: bold; text-align:right">436,915</td>
<td style="font-weight: bold; text-align:right">1,890</td>
<td style="font-weight: bold; text-align:right">122,332,384</td>
<td style="font-weight: bold; text-align:right">1,458,359</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,883,596</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>529</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">6,019</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
<td style="font-weight: bold; text-align:right">35,482,252</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">690,465                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">34,262,104</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">529,683</td>
<td style="font-weight: bold; text-align:right">8,318</td>
<td style="font-weight: bold; text-align:right">164,763</td>
<td style="font-weight: bold; text-align:right">3,206</td>
<td style="font-weight: bold; text-align:right">63,776,166</td>
<td style="font-weight: bold; text-align:right">296,146</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,353,593</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<!-- 1 Case/Death/Test every X -->
<td>6</td><td>312</td><td>3</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">2,460</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>
<td style="font-weight: bold; text-align:right">27,483,568</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+74,714</td>
<td style="font-weight: bold; text-align:right;">30,847                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+54</td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">26,481,961</span></td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+50,411</td>
<td style="text-align:right;font-weight:bold;">970,760</td>
<td style="font-weight: bold; text-align:right">441</td>
<td style="font-weight: bold; text-align:right">535,430</td>
<td style="font-weight: bold; text-align:right">601</td>
<td style="font-weight: bold; text-align:right">15,804,065</td>
<td style="font-weight: bold; text-align:right">307,892</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/south-korea-population/">51,329,899</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>1,664</td><td>3</td>
<td style="font-weight: bold; text-align:right">1,456</td>
<td style="font-weight: bold; text-align:right">1</td>
<td style="font-weight: bold; text-align:right">18,912</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/japan/">Japan</a></td>
<td style="font-weight: bold; text-align:right">25,405,350</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">50,608                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">20,774,961</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">4,579,781</td>
<td style="font-weight: bold; text-align:right">361</td>
<td style="font-weight: bold; text-align:right">202,296</td>
<td style="font-weight: bold; text-align:right">403</td>
<td style="font-weight: bold; text-align:right">82,540,464</td>
<td style="font-weight: bold; text-align:right">657,249</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/japan-population/">125,584,838</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>5</td><td>2,482</td><td>2</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">36,468</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
<td style="font-weight: bold; text-align:right">24,488,080</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">181,733                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">23,799,178</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">507,169</td>
<td style="font-weight: bold; text-align:right">320</td>
<td style="font-weight: bold; text-align:right">406,355</td>
<td style="font-weight: bold; text-align:right">3,016</td>
<td style="font-weight: bold; text-align:right">258,382,332</td>
<td style="font-weight: bold; text-align:right">4,287,595</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,262,770</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>332</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">8,416</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
<td style="font-weight: bold; text-align:right">24,024,746</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">197,253                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">23,761,967</span></td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+3,547</td>
<td style="text-align:right;font-weight:bold;">65,526</td>
<td style="font-weight: bold; text-align:right">146</td>
<td style="font-weight: bold; text-align:right">350,737</td>
<td style="font-weight: bold; text-align:right">2,880</td>
<td style="font-weight: bold; text-align:right">522,526,476</td>
<td style="font-weight: bold; text-align:right">7,628,357</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,497,907</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>347</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">957</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
<td style="font-weight: bold; text-align:right">21,628,829</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">392,342                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">21,030,317</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">206,170</td>
<td style="font-weight: bold; text-align:right">2,300</td>
<td style="font-weight: bold; text-align:right">148,340</td>
<td style="font-weight: bold; text-align:right">2,691</td>
<td style="font-weight: bold; text-align:right">273,400,000</td>
<td style="font-weight: bold; text-align:right">1,875,095</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,805,947</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>7</td><td>372</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">1,414</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/turkey/">Turkey</a></td>
<td style="font-weight: bold; text-align:right">17,005,537</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">101,400                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right;">N/A</td>
<td style="text-align:right;font-weight:bold;">N/A</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">198,751</td>
<td style="font-weight: bold; text-align:right">1,185</td>
<td style="font-weight: bold; text-align:right">162,743,369</td>
<td style="font-weight: bold; text-align:right">1,902,052</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/turkey-population/">85,561,976</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>5</td><td>844</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">1,385</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">12</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/spain/">Spain</a></td>
<td style="font-weight: bold; text-align:right">13,614,807</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">116,108                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">13,403,322</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">95,377</td>
<td style="font-weight: bold; text-align:right">339</td>
<td style="font-weight: bold; text-align:right">291,418</td>
<td style="font-weight: bold; text-align:right">2,485</td>
<td style="font-weight: bold; text-align:right">471,036,328</td>
<td style="font-weight: bold; text-align:right">10,082,298</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/spain-population/">46,719,142</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>402</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">2,041</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">13</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/viet-nam/">Vietnam</a></td>
<td style="font-weight: bold; text-align:right">11,518,511</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">43,178                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">10,609,139</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">866,194</td>
<td style="font-weight: bold; text-align:right">72</td>
<td style="font-weight: bold; text-align:right">116,403</td>
<td style="font-weight: bold; text-align:right">436</td>
<td style="font-weight: bold; text-align:right">85,826,548</td>
<td style="font-weight: bold; text-align:right">867,342</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/viet-nam-population/">98,953,541</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>9</td><td>2,292</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">8,754</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">14</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/australia/">Australia</a></td>
<td style="font-weight: bold; text-align:right">10,763,649</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+4,377</td>
<td style="font-weight: bold; text-align:right;">16,284                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+20</td>
<td style="font-weight: bold; text-align:right">10,546,102</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">201,263</td>
<td style="font-weight: bold; text-align:right">92</td>
<td style="font-weight: bold; text-align:right">412,894</td>
<td style="font-weight: bold; text-align:right">625</td>
<td style="font-weight: bold; text-align:right">78,835,048</td>
<td style="font-weight: bold; text-align:right">3,024,116</td>

In [17]:
for item in range(8, len(tr)):
    td=(tr[item]).find_all('td')
    print(td)

[<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>, <td style="font-weight: bold; text-align:right">100,962,660</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="font-weight: bold; text-align:right;">1,107,794                                </td>, <td style="font-weight: bold;
                                    text-align:right;"></td>, <td style="font-weight: bold; text-align:right">98,374,922</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="text-align:right;font-weight:bold;">1,479,944</td>, <td style="font-weight: bold; text-align:right">3,495</td>, <td style="font-weight: bold; text-align:right">301,556</td>, <td style="font-weight: bold; text-align:right">3,309</td>, <td style="font-weight: bold; text-align:right">1,143,194,153</td>, <td style="font-weight: bold; text-align:right">3,414,505</td>, <td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,805,269</a> </td>, <td data-continent="North America" style="display:none">North America</td>, <td>3</td>, <td>302</td>, <td>0</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right">4,420</td>]
[<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>, <td style="font-weight: bold; text-align:right">44,674,874</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="font-weight: bold; text-align:right;">530,633                                </td>, <td style="font-weight: bold;
                                    text-align:right;"></td>, <td style="font-weight: bold; text-align:right">44,138,805</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="text-align:right;font-weight:bold;">5,436</td>, <td style="font-weight: bold; text-align:right">698</td>, <td style="font-weight: bold; text-align:right">31,760</td>, <td style="font-weight: bold; text-align:right">377</td>, <td style="font-weight: bold; text-align:right">907,369,299</td>, <td style="font-weight: bold; text-align:right">645,065</td>, <td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,406,631,776</a> </td>, <td data-continent="Asia" style="display:none">Asia</td>, <td>31</td>, <td>2,651</td>, <td>2</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right">4</td>]
[<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>, <td style="font-weight: bold; text-align:right">38,184,081</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="font-weight: bold; text-align:right;">159,362                                </td>, <td style="font-weight: bold;
                                    text-align:right;"></td>, <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">37,057,677</span></td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="text-align:right;font-weight:bold;">967,042</td>, <td style="font-weight: bold; text-align:right">869</td>, <td style="font-weight: bold; text-align:right">582,212</td>, <td style="font-weight: bold; text-align:right">2,430</td>, <td style="font-weight: bold; text-align:right">271,490,188</td>, <td style="font-weight: bold; text-align:right">4,139,547</td>, <td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,584,518</a> </td>, <td data-continent="Europe" style="display:none">Europe</td>, <td>2</td>, <td>412</td>, <td>0</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right">14,745</td>]
[<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>, <td style="font-weight: bold; text-align:right">36,649,979</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="font-weight: bold; text-align:right;">158,559                                </td>, <td style="font-weight: bold;
                                    text-align:right;"></td>, <td style="font-weight: bold; text-align:right">35,986,500</td>, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+33,100</td>, <td style="text-align:right;font-weight:bold;">504,920</td>, <td style="font-weight: bold; text-align:right">1,406</td>, <td style="font-weight: bold; text-align:right">436,915</td>, <td style="font-weight: bold; text-align:right">1,890</td>, <td style="font-weight: bold; text-align:right">122,332,384</td>, <td style="font-weight: bold; text-align:right">1,458,359</td>, <td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,883,596</a> </td>, <td data-continent="Europe" style="display:none">Europe</td>, <td>2</td>, <td>529</td>, <td>1</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right">6,019</td>]
[<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>, <td style="font-weight: bold; text-align:right">35,482,252</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="font-weight: bold; text-align:right;">690,465                                </td>, <td style="font-weight: bold;
                                    text-align:right;"></td>, <td style="font-weight: bold; text-align:right">34,262,104</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="text-align:right;font-weight:bold;">529,683</td>, <td style="font-weight: bold; text-align:right">8,318</td>, <td style="font-weight: bold; text-align:right">164,763</td>, <td style="font-weight: bold; text-align:right">3,206</td>, <td style="font-weight: bold; text-align:right">63,776,166</td>, <td style="font-weight: bold; text-align:right">296,146</td>, <td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,353,593</a> </td>, <td data-continent="South America" style="display:none">South America</td>, <td>6</td>, <td>312</td>, <td>3</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right">2,460</td>]
[<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>, <td style="font-weight: bold; text-align:right">27,483,568</td>, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+74,714</td>, <td style="font-weight: bold; text-align:right;">30,847                                </td>, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+54</td>, <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">26,481,961</span></td>, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+50,411</td>, <td style="text-align:right;font-weight:bold;">970,760</td>, <td style="font-weight: bold; text-align:right">441</td>, <td style="font-weight: bold; text-align:right">535,430</td>, <td style="font-weight: bold; text-align:right">601</td>, <td style="font-weight: bold; text-align:right">15,804,065</td>, <td style="font-weight: bold; text-align:right">307,892</td>, <td style="font-weight: bold; text-align:right"><a href="/world-population/south-korea-population/">51,329,899</a> </td>, <td data-continent="Asia" style="display:none">Asia</td>, <td>2</td>, <td>1,664</td>, <td>3</td>, <td style="font-weight: bold; text-align:right">1,456</td>, <td style="font-weight: bold; text-align:right">1</td>, <td style="font-weight: bold; text-align:right">18,912</td>]
[<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/japan/">Japan</a></td>, <td style="font-weight: bold; text-align:right">25,405,350</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="font-weight: bold; text-align:right;">50,608                                </td>, <td style="font-weight: bold;
                                    text-align:right;"></td>, <td style="font-weight: bold; text-align:right">20,774,961</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="text-align:right;font-weight:bold;">4,579,781</td>, <td style="font-weight: bold; text-align:right">361</td>, <td style="font-weight: bold; text-align:right">202,296</td>, <td style="font-weight: bold; text-align:right">403</td>, <td style="font-weight: bold; text-align:right">82,540,464</td>, <td style="font-weight: bold; text-align:right">657,249</td>, <td style="font-weight: bold; text-align:right"><a href="/world-population/japan-population/">125,584,838</a> </td>, <td data-continent="Asia" style="display:none">Asia</td>, <td>5</td>, <td>2,482</td>, <td>2</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right">36,468</td>]
[<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>, <td style="font-weight: bold; text-align:right">24,488,080</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="font-weight: bold; text-align:right;">181,733                                </td>, <td style="font-weight: bold;
                                    text-align:right;"></td>, <td style="font-weight: bold; text-align:right">23,799,178</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="text-align:right;font-weight:bold;">507,169</td>, <td style="font-weight: bold; text-align:right">320</td>, <td style="font-weight: bold; text-align:right">406,355</td>, <td style="font-weight: bold; text-align:right">3,016</td>, <td style="font-weight: bold; text-align:right">258,382,332</td>, <td style="font-weight: bold; text-align:right">4,287,595</td>, <td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,262,770</a> </td>, <td data-continent="Europe" style="display:none">Europe</td>, <td>2</td>, <td>332</td>, <td>0</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right">8,416</td>]
[<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>, <td style="font-weight: bold; text-align:right">24,024,746</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="font-weight: bold; text-align:right;">197,253                                </td>, <td style="font-weight: bold;
                                    text-align:right;"></td>, <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">23,761,967</span></td>, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+3,547</td>, <td style="text-align:right;font-weight:bold;">65,526</td>, <td style="font-weight: bold; text-align:right">146</td>, <td style="font-weight: bold; text-align:right">350,737</td>, <td style="font-weight: bold; text-align:right">2,880</td>, <td style="font-weight: bold; text-align:right">522,526,476</td>, <td style="font-weight: bold; text-align:right">7,628,357</td>, <td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,497,907</a> </td>, <td data-continent="Europe" style="display:none">Europe</td>, <td>3</td>, <td>347</td>, <td>0</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right">957</td>]
[<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>, <td style="font-weight: bold; text-align:right">21,628,829</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="font-weight: bold; text-align:right;">392,342                                </td>, <td style="font-weight: bold;
                                    text-align:right;"></td>, <td style="font-weight: bold; text-align:right">21,030,317</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="text-align:right;font-weight:bold;">206,170</td>, <td style="font-weight: bold; text-align:right">2,300</td>, <td style="font-weight: bold; text-align:right">148,340</td>, <td style="font-weight: bold; text-align:right">2,691</td>, <td style="font-weight: bold; text-align:right">273,400,000</td>, <td style="font-weight: bold; text-align:right">1,875,095</td>, <td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,805,947</a> </td>, <td data-continent="Europe" style="display:none">Europe</td>, <td>7</td>, <td>372</td>, <td>1</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right">1,414</td>]
[<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/turkey/">Turkey</a></td>, <td style="font-weight: bold; text-align:right">17,005,537</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="font-weight: bold; text-align:right;">101,400                                </td>, <td style="font-weight: bold;
                                    text-align:right;"></td>, <td style="font-weight: bold; text-align:right">N/A</td>, <td style="font-weight: bold; text-align:right;">N/A</td>, <td style="text-align:right;font-weight:bold;">N/A</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right">198,751</td>, <td style="font-weight: bold; text-align:right">1,185</td>, <td style="font-weight: bold; text-align:right">162,743,369</td>, <td style="font-weight: bold; text-align:right">1,902,052</td>, <td style="font-weight: bold; text-align:right"><a href="/world-population/turkey-population/">85,561,976</a> </td>, <td data-continent="Asia" style="display:none">Asia</td>, <td>5</td>, <td>844</td>, <td>1</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right">1,385</td>]
[<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">12</td>, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/spain/">Spain</a></td>, <td style="font-weight: bold; text-align:right">13,614,807</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="font-weight: bold; text-align:right;">116,108                                </td>, <td style="font-weight: bold;
                                    text-align:right;"></td>, <td style="font-weight: bold; text-align:right">13,403,322</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="text-align:right;font-weight:bold;">95,377</td>, <td style="font-weight: bold; text-align:right">339</td>, <td style="font-weight: bold; text-align:right">291,418</td>, <td style="font-weight: bold; text-align:right">2,485</td>, <td style="font-weight: bold; text-align:right">471,036,328</td>, <td style="font-weight: bold; text-align:right">10,082,298</td>, <td style="font-weight: bold; text-align:right"><a href="/world-population/spain-population/">46,719,142</a> </td>, <td data-continent="Europe" style="display:none">Europe</td>, <td>3</td>, <td>402</td>, <td>0</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right">2,041</td>]
[<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">13</td>, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/viet-nam/">Vietnam</a></td>, <td style="font-weight: bold; text-align:right">11,518,511</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="font-weight: bold; text-align:right;">43,178                                </td>, <td style="font-weight: bold;
                                    text-align:right;"></td>, <td style="font-weight: bold; text-align:right">10,609,139</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="text-align:right;font-weight:bold;">866,194</td>, <td style="font-weight: bold; text-align:right">72</td>, <td style="font-weight: bold; text-align:right">116,403</td>, <td style="font-weight: bold; text-align:right">436</td>, <td style="font-weight: bold; text-align:right">85,826,548</td>, <td style="font-weight: bold; text-align:right">867,342</td>, <td style="font-weight: bold; text-align:right"><a href="/world-population/viet-nam-population/">98,953,541</a> </td>, <td data-continent="Asia" style="display:none">Asia</td>, <td>9</td>, <td>2,292</td>, <td>1</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right">8,754</td>]
[<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">14</td>, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/australia/">Australia</a></td>, <td style="font-weight: bold; text-align:right">10,763,649</td>, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+4,377</td>, <td style="font-weight: bold; text-align:right;">16,284                                </td>, <td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+20</td>, <td style="font-weight: bold; text-align:right">10,546,102</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="text-align:right;font-weight:bold;">201,263</td>, <td style="font-weight: bold; text-align:right">92</td>, <td style="font-weight: bold; text-align:right">412,894</td>, <td style="font-weight: bold; text-align:right">625</td>, <td style="font-weight: bold; text-align:right">78,835,048</td>, <td style="font-weight: bold; text-align:right">3,024,116</td>, <td style="font-weight: bold; text-align:right"><a href="/world-population/australia-population/">26,068,792</a> </td>, <td data-continent="Australia/Oceania" style="display:none">Australia/Oceania</td>, <td>2</td>, <td>1,601</td>, <td>0</td>, <td style="font-weight: bold; text-align:right">168</td>, <td style="font-weight: bold; text-align:right">0.8</td>, <td style="font-weight: bold; text-align:right">7,720</td>]

[<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">220</td>, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/falkland-islands-malvinas/">Falkland Islands</a></td>, <td style="font-weight: bold; text-align:right">1,930</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="font-weight: bold; text-align:right;"> </td>, <td style="font-weight: bold;
                                    text-align:right;"></td>, <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">1,930</span></td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="text-align:right;font-weight:bold;">0</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right">545,352</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right">8,632</td>, <td style="font-weight: bold; text-align:right">2,439,107</td>, <td style="font-weight: bold; text-align:right"><a href="/world-population/falkland-islands-malvinas-population/">3,539</a> </td>, <td data-continent="South America" style="display:none">South America</td>, <td>2</td>, <td></td>, <td>0</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>]
[<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">221</td>, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/saint-helena/">Saint Helena</a></td>, <td style="font-weight: bold; text-align:right">1,806</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="font-weight: bold; text-align:right;"> </td>, <td style="font-weight: bold;
                                    text-align:right;"></td>, <td style="font-weight: bold; text-align:right">2</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="text-align:right;font-weight:bold;">1,804</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right">295,339</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"><a href="/world-population/saint-helena-population/">6,115</a> </td>, <td data-continent="Africa" style="display:none">Africa</td>, <td>3</td>, <td></td>, <td></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right">295,012</td>]
[<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">222</td>, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/montserrat/">Montserrat</a></td>, <td style="font-weight: bold; text-align:right">1,403</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="font-weight: bold; text-align:right;">8                                </td>, <td style="font-weight: bold;
                                    text-align:right;"></td>, <td style="font-weight: bold; text-align:right">1,376</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="text-align:right;font-weight:bold;">19</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right">282,578</td>, <td style="font-weight: bold; text-align:right">1,611</td>, <td style="font-weight: bold; text-align:right">17,762</td>, <td style="font-weight: bold; text-align:right">3,577,442</td>, <td style="font-weight: bold; text-align:right"><a href="/world-population/montserrat-population/">4,965</a> </td>, <td data-continent="North America" style="display:none">North America</td>, <td>4</td>, <td>621</td>, <td>0</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right">3,827</td>]
[<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">223</td>, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/china-macao-sar/">Macao</a></td>, <td style="font-weight: bold; text-align:right">827</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="font-weight: bold; text-align:right;">6                                </td>, <td style="font-weight: bold;
                                    text-align:right;"></td>, <td style="font-weight: bold; text-align:right">791</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="text-align:right;font-weight:bold;">30</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right">1,239</td>, <td style="font-weight: bold; text-align:right">9</td>, <td style="font-weight: bold; text-align:right">7,850</td>, <td style="font-weight: bold; text-align:right">11,760</td>, <td style="font-weight: bold; text-align:right"><a href="/world-population/china-macao-sar-population/">667,490</a> </td>, <td data-continent="Asia" style="display:none">Asia</td>, <td>807</td>, <td>111,248</td>, <td>85</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right">45</td>]
[<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">224</td>, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/wallis-and-futuna-islands/">Wallis and Futuna</a></td>, <td style="font-weight: bold; text-align:right">761</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="font-weight: bold; text-align:right;">7                                </td>, <td style="font-weight: bold;
                                    text-align:right;"></td>, <td style="font-weight: bold; text-align:right">438</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="text-align:right;font-weight:bold;">316</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right">69,295</td>, <td style="font-weight: bold; text-align:right">637</td>, <td style="font-weight: bold; text-align:right">20,508</td>, <td style="font-weight: bold; text-align:right">1,867,419</td>, <td style="font-weight: bold; text-align:right"><a href="/world-population/wallis-and-futuna-islands-population/">10,982</a> </td>, <td data-continent="Australia/Oceania" style="display:none">Australia/Oceania</td>, <td>14</td>, <td>1,569</td>, <td>1</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right">28,774</td>]
[<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">225</td>, <td style="font-weight: bold; font-size:15px; text-align:left;"><span style="color:#00B5F0; font-style:italic; ">Diamond Princess</span></td>, <td style="font-weight: bold; text-align:right">712</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="font-weight: bold; text-align:right;">13                                </td>, <td style="font-weight: bold;
                                    text-align:right;"></td>, <td style="font-weight: bold; text-align:right">699</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="text-align:right;font-weight:bold;">0</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"> </td>, <td data-continent="" style="display:none"></td>, <td></td>, <td></td>, <td></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>]
[<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">226</td>, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/niue/">Niue</a></td>, <td style="font-weight: bold; text-align:right">180</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="font-weight: bold; text-align:right;"> </td>, <td style="font-weight: bold;
                                    text-align:right;"></td>, <td style="font-weight: bold; text-align:right">114</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="text-align:right;font-weight:bold;">66</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right">110,974</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"><a href="/world-population/niue-population/">1,622</a> </td>, <td data-continent="Australia/Oceania" style="display:none">Australia/Oceania</td>, <td>9</td>, <td></td>, <td></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right">40,691</td>]
[<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">227</td>, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/holy-see/">Vatican City</a></td>, <td style="font-weight: bold; text-align:right">29</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="font-weight: bold; text-align:right;"> </td>, <td style="font-weight: bold;
                                    text-align:right;"></td>, <td style="font-weight: bold; text-align:right">29</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="text-align:right;font-weight:bold;">0</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right">36,295</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"><a href="/world-population/holy-see-population/">799</a> </td>, <td data-continent="Europe" style="display:none">Europe</td>, <td>28</td>, <td></td>, <td></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>]
[<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">228</td>, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/western-sahara/">Western Sahara</a></td>, <td style="font-weight: bold; text-align:right">10</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="font-weight: bold; text-align:right;">1                                </td>, <td style="font-weight: bold;
                                    text-align:right;"></td>, <td style="font-weight: bold; text-align:right">9</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="text-align:right;font-weight:bold;">0</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right">16</td>, <td style="font-weight: bold; text-align:right">2</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"><a href="/world-population/western-sahara-population/">626,161</a> </td>, <td data-continent="Africa" style="display:none">Africa</td>, <td>62,616</td>, <td>626,161</td>, <td></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>]
[<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">229</td>, <td style="font-weight: bold; font-size:15px; text-align:left;"><span style="color:#00B5F0; font-style:italic; ">MS Zaandam</span></td>, <td style="font-weight: bold; text-align:right">9</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="font-weight: bold; text-align:right;">2                                </td>, <td style="font-weight: bold;
                                    text-align:right;"></td>, <td style="font-weight: bold; text-align:right">7</td>, <td style="font-weight: bold; text-align:right;"></td>, <td style="text-align:right;font-weight:bold;">0</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"> </td>, <td data-continent="" style="display:none"></td>, <td></td>, <td></td>, <td></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right"></td>]
[<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">230</td>, <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/china/">China</a></td>, <td style="font-weight: bold; text-align:right">349,938</td>, <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+4,409</td>, <td style="font-weight: bold; text-align:right;">5,235                                </td>, <td style="font-weight: bold;
                                    text-align:right;"></td>, <td style="font-weight: bold; text-align:right">301,748</td>, <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+3,935</td>, <td style="text-align:right;font-weight:bold;">42,955</td>, <td style="font-weight: bold; text-align:right">128</td>, <td style="font-weight: bold; text-align:right">242</td>, <td style="font-weight: bold; text-align:right">4</td>, <td style="font-weight: bold; text-align:right">160,000,000</td>, <td style="font-weight: bold; text-align:right">110,461</td>, <td style="font-weight: bold; text-align:right">1,448,471,400                                </td>, <td data-continent="Asia" style="display:none">Asia</td>, <td>4,139</td>, <td>276,690</td>, <td>9</td>, <td style="font-weight: bold; text-align:right">3</td>, <td style="font-weight: bold; text-align:right"></td>, <td style="font-weight: bold; text-align:right">30</td>]

In [18]:
# [[1, 'usa', 55655, 5587], [2, 'india', 554, 888]]

In [19]:
complete_data = []
for item in range(8, len(tr)):
    country_data = []
    table_row = tr[item]
    td = table_row.find_all('td') # one table row has multiple table data
    for item in td:
        country_data.append(item.text) # extract data of each country
    complete_data.append(country_data) # append all data of each country on a list

In [20]:
clean_data = list(map(lambda x: x[1:10], complete_data))

In [21]:
clean_data

[['USA',
  '100,962,660',
  '',
  '1,107,794                                ',
  '',
  '98,374,922',
  '',
  '1,479,944',
  '3,495'],
 ['India',
  '44,674,874',
  '',
  '530,633                                ',
  '',
  '44,138,805',
  '',
  '5,436',
  '698'],
 ['France',
  '38,184,081',
  '',
  '159,362                                ',
  '',
  '37,057,677',
  '',
  '967,042',
  '869'],
 ['Germany',
  '36,649,979',
  '',
  '158,559                                ',
  '',
  '35,986,500',
  '+33,100',
  '504,920',
  '1,406'],
 ['Brazil',
  '35,482,252',
  '',
  '690,465                                ',
  '',
  '34,262,104',
  '',
  '529,683',
  '8,318'],
 ['S. Korea',
  '27,483,568',
  '+74,714',
  '30,847                                ',
  '+54',
  '26,481,961',
  '+50,411',
  '970,760',
  '441'],
 ['Japan',
  '25,405,350',
  '',
  '50,608                                ',
  '',
  '20,774,961',
  '',
  '4,579,781',
  '361'],
 ['Italy',
  '24,488,080',
  '',
  '181,733                                ',
  '',
  '23,799,178',
  '',
  '507,169',
  '320'],
 ['UK',
  '24,024,746',
  '',
  '197,253                                ',
  '',
  '23,761,967',
  '+3,547',
  '65,526',
  '146'],
 ['Russia',
  '21,628,829',
  '',
  '392,342                                ',
  '',
  '21,030,317',
  '',
  '206,170',
  '2,300'],
 ['Turkey',
  '17,005,537',
  '',
  '101,400                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  ''],
 ['Spain',
  '13,614,807',
  '',
  '116,108                                ',
  '',
  '13,403,322',
  '',
  '95,377',
  '339'],
 ['Vietnam',
  '11,518,511',
  '',
  '43,178                                ',
  '',
  '10,609,139',
  '',
  '866,194',
  '72'],
 ['Australia',
  '10,763,649',
  '+4,377',
  '16,284                                ',
  '+20',
  '10,546,102',
  '',
  '201,263',
  '92'],
 ['Argentina',
  '9,739,856',
  '',
  '130,034                                ',
  '',
  '9,591,684',
  '',
  '18,138',
  '241'],
 ['Netherlands',
  '8,547,416',
  '',
  '22,926                                ',
  '',
  '8,500,604',
  '',
  '23,886',
  '43'],
 ['Taiwan',
  '8,395,477',
  '',
  '14,522                                ',
  '',
  '8,077,585',
  '',
  '303,370',
  ''],
 ['Iran',
  '7,559,958',
  '',
  '144,648                                ',
  '',
  '7,335,357',
  '',
  '79,953',
  '72'],
 ['Mexico',
  '7,145,409',
  '',
  '330,592                                ',
  '',
  '6,407,215',
  '',
  '407,602',
  '4,798'],
 ['Indonesia',
  '6,686,181',
  '',
  '160,071                                ',
  '',
  '6,478,450',
  '',
  '47,660',
  '2,771'],
 ['Poland',
  '6,355,424',
  '',
  '118,347                                ',
  '',
  '5,335,940',
  '',
  '901,137',
  '1,530'],
 ['Colombia',
  '6,318,021',
  '',
  '141,911                                ',
  '',
  '6,142,640',
  '',
  '33,470',
  '342'],
 ['Austria',
  '5,588,468',
  '',
  '21,242                                ',
  '',
  '5,521,209',
  '',
  '46,017',
  '47'],
 ['Portugal',
  '5,546,290',
  '',
  '25,517                                ',
  '',
  '5,503,077',
  '+1,135',
  '17,696',
  '61'],
 ['Greece',
  '5,404,690',
  '',
  '34,309                                ',
  '',
  '5,351,445',
  '+6,312',
  '18,936',
  '115'],
 ['Ukraine',
  '5,341,284',
  '',
  '110,586                                ',
  '',
  '5,218,950',
  '+1,047',
  '11,748',
  ''],
 ['Malaysia',
  '5,003,557',
  '',
  '36,732                                ',
  '',
  '4,945,067',
  '',
  '21,758',
  '101'],
 ['Chile',
  '4,941,227',
  '',
  '62,597                                ',
  '',
  '4,867,554',
  '',
  '11,076',
  '129'],
 ['DPRK',
  '4,772,813',
  '',
  '74                                ',
  '',
  '4,772,739',
  '',
  '0',
  ''],
 ['Israel',
  '4,730,502',
  '',
  '11,882                                ',
  '',
  '4,704,016',
  '',
  '14,604',
  '22'],
 ['Thailand',
  '4,711,528',
  '',
  '33,285                                ',
  '',
  '4,649,509',
  '',
  '28,734',
  '1,496'],
 ['Belgium',
  '4,644,478',
  '',
  '33,086                                ',
  '',
  '4,586,036',
  '',
  '25,356',
  '48'],
 ['Czechia',
  '4,562,887',
  '',
  '41,923                                ',
  '',
  '4,512,355',
  '',
  '8,609',
  '46'],
 ['Canada',
  '4,423,053',
  '',
  '48,044                                ',
  '',
  '4,314,332',
  '+2,449',
  '60,677',
  '99'],
 ['Switzerland',
  '4,317,035',
  '',
  '14,318                                ',
  '',
  '4,237,770',
  '+1,721',
  '64,947',
  '53'],
 ['Peru',
  '4,304,745',
  '',
  '217,519                                ',
  '',
  '3,985,710',
  '',
  '101,516',
  '111'],
 ['South Africa',
  '4,043,242',
  '',
  '102,464                                ',
  '',
  '3,912,506',
  '',
  '28,272',
  '192'],
 ['Philippines',
  '4,042,936',
  '',
  '64,770                                ',
  '',
  '3,960,685',
  '',
  '17,481',
  '162'],
 ['Romania',
  '3,298,738',
  '',
  '67,289                                ',
  '',
  '3,227,158',
  '+215',
  '4,291',
  '101'],
 ['Denmark',
  '3,150,954',
  '',
  '7,557                                ',
  '',
  '3,136,803',
  '',
  '6,594',
  '9'],
 ['Sweden',
  '2,632,091',
  '',
  '21,095                                ',
  '',
  '2,596,044',
  '+153',
  '14,952',
  '19'],
 ['Iraq',
  '2,464,375',
  '',
  '25,366                                ',
  '',
  '2,437,963',
  '',
  '1,046',
  '21'],
 ['Serbia',
  '2,426,848',
  '',
  '17,418                                ',
  '',
  '2,399,353',
  '',
  '10,077',
  '23'],
 ['Hong Kong',
  '2,177,436',
  '',
  '10,842                                ',
  '',
  '1,907,866',
  '',
  '258,728',
  '21'],
 ['Singapore',
  '2,174,989',
  '',
  '1,706                                ',
  '',
  '2,099,889',
  '',
  '73,394',
  '8'],
 ['Hungary',
  '2,166,352',
  '',
  '48,287                                ',
  '',
  '2,104,358',
  '',
  '13,707',
  '7'],
 ['Bangladesh',
  '2,036,685',
  '',
  '29,435                                ',
  '',
  '1,986,210',
  '',
  '21,040',
  '1,331'],
 ['New Zealand',
  '1,979,614',
  '',
  '3,337                                ',
  '',
  '1,942,897',
  '',
  '33,380',
  ''],
 ['Slovakia',
  '1,856,552',
  '',
  '20,745                                ',
  '',
  '1,834,384',
  '',
  '1,423',
  '23'],
 ['Georgia',
  '1,806,918',
  '',
  '16,882                                ',
  '',
  '1,776,548',
  '',
  '13,488',
  ''],
 ['Jordan',
  '1,746,997',
  '',
  '14,122                                ',
  '',
  '1,731,007',
  '',
  '1,868',
  '59'],
 ['Ireland',
  '1,680,548',
  '',
  '8,159                                ',
  '',
  '1,667,043',
  '+191',
  '5,346',
  '10'],
 ['Pakistan',
  '1,575,383',
  '+28',
  '30,634                                ',
  '+2',
  '1,538,689',
  '',
  '6,060',
  '35'],
 ['Norway',
  '1,469,983',
  '',
  '4,325                                ',
  '',
  '1,463,130',
  '',
  '2,528',
  '20'],
 ['Finland',
  '1,405,255',
  '',
  '7,448                                ',
  '',
  '1,372,645',
  '+1,855',
  '25,162',
  '21'],
 ['Kazakhstan',
  '1,397,667',
  '',
  '13,693                                ',
  '',
  '1,382,292',
  '',
  '1,682',
  '24'],
 ['Bulgaria',
  '1,288,196',
  '',
  '38,053                                ',
  '',
  '1,245,714',
  '',
  '4,429',
  '40'],
 ['Lithuania',
  '1,278,458',
  '',
  '9,439                                ',
  '',
  '1,262,876',
  '',
  '6,143',
  '8'],
 ['Morocco',
  '1,269,570',
  '',
  '16,286                                ',
  '',
  '1,252,212',
  '',
  '1,072',
  '293'],
 ['Slovenia',
  '1,266,751',
  '',
  '6,944                                ',
  '',
  '1,242,639',
  '',
  '17,168',
  '17'],
 ['Croatia',
  '1,255,155',
  '',
  '17,364                                ',
  '',
  '1,235,663',
  '',
  '2,128',
  '9'],
 ['Lebanon',
  '1,220,800',
  '',
  '10,740                                ',
  '',
  '1,087,587',
  '',
  '122,473',
  '74'],
 ['Guatemala',
  '1,161,983',
  '',
  '19,958                                ',
  '',
  '1,133,955',
  '',
  '8,070',
  '5'],
 ['Costa Rica',
  '1,148,914',
  '',
  '9,046                                ',
  '',
  '860,711',
  '',
  '279,157',
  '52'],
 ['Tunisia',
  '1,147,145',
  '',
  '29,269                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '44'],
 ['Bolivia',
  '1,112,997',
  '',
  '22,251                                ',
  '',
  '1,078,596',
  '',
  '12,150',
  '220'],
 ['Cuba',
  '1,111,452',
  '',
  '8,530                                ',
  '',
  '1,102,815',
  '',
  '107',
  '23'],
 ['UAE',
  '1,044,934',
  '',
  '2,348                                ',
  '',
  '1,025,215',
  '',
  '17,371',
  ''],
 ['Ecuador',
  '1,011,132',
  '',
  '35,940                                ',
  '',
  '973,448',
  '',
  '1,744',
  '759'],
 ['Panama',
  '1,009,252',
  '',
  '8,533                                ',
  '',
  '991,093',
  '',
  '9,626',
  '16'],
 ['Nepal',
  '1,000,912',
  '',
  '12,019                                ',
  '',
  '988,814',
  '',
  '79',
  ''],
 ['Uruguay',
  '995,402',
  '',
  '7,541                                ',
  '',
  '986,371',
  '',
  '1,490',
  '18'],
 ['Belarus',
  '994,037',
  '',
  '7,118                                ',
  '',
  '985,592',
  '',
  '1,327',
  ''],
 ['Mongolia',
  '993,705',
  '',
  '2,179                                ',
  '',
  '988,552',
  '',
  '2,974',
  '192'],
 ['Latvia',
  '966,131',
  '',
  '6,105                                ',
  '',
  '950,319',
  '',
  '9,707',
  '3'],
 ['Saudi Arabia',
  '825,936',
  '',
  '9,476                                ',
  '',
  '813,405',
  '',
  '3,055',
  '27'],
 ['Azerbaijan',
  '824,574',
  '',
  '9,984                                ',
  '',
  '814,298',
  '',
  '292',
  ''],
 ['Paraguay',
  '777,525',
  '',
  '19,630                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '7'],
 ['Bahrain',
  '696,851',
  '',
  '1,536                                ',
  '',
  '694,364',
  '',
  '951',
  '2'],
 ['Sri Lanka',
  '671,719',
  '',
  '16,806                                ',
  '',
  '654,892',
  '',
  '21',
  ''],
 ['Kuwait',
  '662,747',
  '',
  '2,570                                ',
  '',
  '660,095',
  '',
  '82',
  ''],
 ['Dominican Republic',
  '650,990',
  '',
  '4,384                                ',
  '',
  '644,785',
  '',
  '1,821',
  '4'],
 ['Myanmar',
  '633,341',
  '',
  '19,488                                ',
  '',
  '607,877',
  '',
  '5,976',
  ''],
 ['Palestine',
  '620,816',
  '',
  '5,404                                ',
  '',
  '614,962',
  '',
  '450',
  '17'],
 ['Cyprus',
  '618,248',
  '',
  '1,237                                ',
  '',
  '605,050',
  '',
  '11,961',
  '60'],
 ['Estonia',
  '609,769',
  '',
  '2,799                                ',
  '',
  '524,990',
  '',
  '81,980',
  '5'],
 ['Moldova',
  '595,402',
  '',
  '11,920                                ',
  '',
  '504,142',
  '',
  '79,340',
  '49'],
 ['Venezuela',
  '547,891',
  '',
  '5,829                                ',
  '',
  '540,991',
  '',
  '1,071',
  '36'],
 ['Egypt',
  '515,645',
  '',
  '24,613                                ',
  '',
  '442,182',
  '',
  '48,850',
  '122'],
 ['Libya',
  '507,100',
  '',
  '6,437                                ',
  '',
  '500,610',
  '',
  '53',
  ''],
 ['Ethiopia',
  '494,857',
  '',
  '7,572                                ',
  '',
  '472,547',
  '',
  '14,738',
  '1'],
 ['Qatar',
  '481,904',
  '',
  '685                                ',
  '',
  '478,981',
  '',
  '2,238',
  ''],
 ['Réunion',
  '477,305',
  '',
  '903                                ',
  '',
  '418,572',
  '',
  '57,830',
  '10'],
 ['Honduras',
  '458,921',
  '',
  '11,051                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '105'],
 ['Armenia',
  '445,828',
  '',
  '8,712                                ',
  '',
  '434,979',
  '',
  '2,137',
  ''],
 ['Bosnia and Herzegovina',
  '400,613',
  '',
  '16,207                                ',
  '',
  '378,468',
  '',
  '5,938',
  ''],
 ['Oman',
  '399,119',
  '',
  '4,260                                ',
  '',
  '384,669',
  '',
  '10,190',
  '2'],
 ['North Macedonia',
  '345,067',
  '',
  '9,591                                ',
  '',
  '335,261',
  '',
  '215',
  ''],
 ['Kenya',
  '341,977',
  '',
  '5,684                                ',
  '',
  '335,740',
  '',
  '553',
  '1'],
 ['Zambia',
  '333,746',
  '',
  '4,019                                ',
  '',
  '329,690',
  '',
  '37',
  ''],
 ['Albania',
  '333,455',
  '',
  '3,593                                ',
  '',
  '328,263',
  '',
  '1,599',
  ''],
 ['Botswana',
  '326,800',
  '',
  '2,793                                ',
  '',
  '323,747',
  '',
  '260',
  '1'],
 ['Luxembourg',
  '297,757',
  '',
  '1,133                                ',
  '',
  '288,991',
  '',
  '7,633',
  ''],
 ['Montenegro',
  '283,895',
  '',
  '2,790                                ',
  '',
  '280,846',
  '',
  '259',
  '6'],
 ['Algeria',
  '271,122',
  '',
  '6,881                                ',
  '',
  '182,586',
  '',
  '81,655',
  ''],
 ['Nigeria',
  '266,283',
  '',
  '3,155                                ',
  '',
  '259,640',
  '',
  '3,488',
  '11'],
 ['Zimbabwe',
  '259,356',
  '',
  '5,622                                ',
  '',
  '253,061',
  '',
  '673',
  '12'],
 ['Uzbekistan',
  '247,424',
  '',
  '1,637                                ',
  '',
  '241,486',
  '',
  '4,301',
  '23'],
 ['Brunei ',
  '241,044',
  '',
  '225                                ',
  '',
  '222,140',
  '',
  '18,679',
  '3'],
 ['Mozambique',
  '230,624',
  '',
  '2,226                                ',
  '',
  '228,310',
  '',
  '88',
  '11'],
 ['Martinique',
  '224,468',
  '',
  '1,071                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '8'],
 ['Laos',
  '216,988',
  '+69',
  '758                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  ''],
 ['Iceland',
  '207,504',
  '',
  '219                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '2'],
 ['Kyrgyzstan',
  '206,543',
  '',
  '2,991                                ',
  '',
  '196,406',
  '',
  '7,146',
  '131'],
 ['Afghanistan',
  '206,331',
  '',
  '7,835                                ',
  '',
  '184,079',
  '',
  '14,417',
  '1,124'],
 ['El Salvador',
  '201,785',
  '',
  '4,230                                ',
  '',
  '179,410',
  '',
  '18,145',
  '8'],
 ['Guadeloupe',
  '197,918',
  '',
  '995                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '19'],
 ['Maldives',
  '185,632',
  '',
  '311                                ',
  '',
  '163,687',
  '',
  '21,634',
  '25'],
 ['Trinidad and Tobago',
  '185,528',
  '',
  '4,268                                ',
  '',
  '181,075',
  '',
  '185',
  '8'],
 ['Ghana',
  '171,023',
  '',
  '1,461                                ',
  '',
  '169,553',
  '',
  '9',
  '2'],
 ['Namibia',
  '169,946',
  '',
  '4,080                                ',
  '',
  '165,826',
  '',
  '40',
  ''],
 ['Uganda',
  '169,810',
  '',
  '3,630                                ',
  '',
  '100,431',
  '',
  '65,749',
  '3'],
 ['Jamaica',
  '152,517',
  '',
  '3,399                                ',
  '',
  '99,392',
  '',
  '49,726',
  ''],
 ['Cambodia',
  '138,176',
  '',
  '3,056                                ',
  '',
  '135,035',
  '',
  '85',
  ''],
 ['Rwanda',
  '132,811',
  '',
  '1,467                                ',
  '',
  '131,112',
  '',
  '232',
  ''],
 ['Cameroon',
  '123,993',
  '',
  '1,965                                ',
  '',
  '118,616',
  '',
  '3,412',
  '13'],
 ['Malta',
  '115,907',
  '',
  '809                                ',
  '',
  '114,518',
  '',
  '580',
  '4'],
 ['Angola',
  '104,750',
  '',
  '1,925                                ',
  '',
  '102,538',
  '',
  '287',
  ''],
 ['Barbados',
  '104,416',
  '',
  '567                                ',
  '',
  '102,435',
  '',
  '1,414',
  ''],
 ['French Guiana',
  '96,389',
  '',
  '411                                ',
  '',
  '11,254',
  '',
  '84,724',
  '2'],
 ['Channel Islands',
  '96,208',
  '',
  '208                                ',
  '',
  '95,434',
  '',
  '566',
  ''],
 ['DRC',
  '94,452',
  '',
  '1,456                                ',
  '',
  '83,728',
  '',
  '9,268',
  ''],
 ['Senegal',
  '88,887',
  '',
  '1,968                                ',
  '',
  '86,887',
  '',
  '32',
  ''],
 ['Malawi',
  '88,086',
  '',
  '2,685                                ',
  '',
  '85,009',
  '',
  '392',
  '67'],
 ['Ivory Coast',
  '87,890',
  '',
  '830                                ',
  '',
  '87,053',
  '',
  '7',
  ''],
 ['Suriname',
  '81,581',
  '',
  '1,393                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  ''],
 ['French Polynesia',
  '77,275',
  '',
  '649                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '7'],
 ['New Caledonia',
  '77,127',
  '',
  '314                                ',
  '',
  '75,257',
  '',
  '1,556',
  '9'],
 ['Eswatini',
  '73,908',
  '',
  '1,422                                ',
  '',
  '72,392',
  '',
  '94',
  ''],
 ['Guyana',
  '71,679',
  '',
  '1,285                                ',
  '',
  '70,233',
  '',
  '161',
  ''],
 ['Belize',
  '69,117',
  '',
  '688                                ',
  '',
  '68,379',
  '',
  '50',
  '6'],
 ['Fiji',
  '68,451',
  '',
  '878                                ',
  '',
  '66,524',
  '',
  '1,049',
  ''],
 ['Madagascar',
  '67,488',
  '',
  '1,413                                ',
  '',
  '65,602',
  '',
  '473',
  ''],
 ['Sudan',
  '63,655',
  '',
  '4,991                                ',
  '',
  '58,083',
  '',
  '581',
  ''],
 ['Mauritania',
  '63,421',
  '',
  '997                                ',
  '',
  '62,421',
  '',
  '3',
  ''],
 ['Cabo Verde',
  '63,095',
  '',
  '412                                ',
  '',
  '62,563',
  '',
  '120',
  '23'],
 ['Bhutan',
  '62,512',
  '',
  '21                                ',
  '',
  '61,564',
  '',
  '927',
  ''],
 ['Syria',
  '57,409',
  '',
  '3,163                                ',
  '',
  '54,239',
  '',
  '7',
  ''],
 ['Burundi',
  '51,018',
  '',
  '38                                ',
  '',
  '50,638',
  '',
  '342',
  ''],
 ['Seychelles',
  '50,068',
  '',
  '171                                ',
  '',
  '49,606',
  '',
  '291',
  ''],
 ['Gabon',
  '48,973',
  '',
  '306                                ',
  '',
  '48,582',
  '',
  '85',
  ''],
 ['Andorra',
  '47,219',
  '',
  '157                                ',
  '',
  '46,731',
  '',
  '331',
  '14'],
 ['Papua New Guinea',
  '46,247',
  '',
  '668                                ',
  '',
  '43,982',
  '',
  '1,597',
  '7'],
 ['Curaçao',
  '45,986',
  '',
  '295                                ',
  '',
  '44,720',
  '',
  '971',
  '3'],
 ['Aruba',
  '43,641',
  '',
  '236                                ',
  '',
  '42,438',
  '',
  '967',
  '2'],
 ['Mayotte',
  '41,679',
  '',
  '187                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  ''],
 ['Mauritius',
  '41,175',
  '',
  '1,035                                ',
  '',
  '39,396',
  '',
  '744',
  ''],
 ['Tanzania',
  '40,806',
  '',
  '845                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '7'],
 ['Togo',
  '39,332',
  '',
  '290                                ',
  '',
  '39,035',
  '',
  '7',
  ''],
 ['Guinea',
  '38,153',
  '',
  '464                                ',
  '',
  '37,218',
  '',
  '471',
  '8'],
 ['Isle of Man',
  '38,008',
  '',
  '116                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  ''],
 ['Bahamas',
  '37,491',
  '',
  '833                                ',
  '',
  '36,366',
  '',
  '292',
  '1'],
 ['Faeroe Islands',
  '34,658',
  '',
  '28                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '5'],
 ['Lesotho',
  '34,490',
  '',
  '706                                ',
  '',
  '25,980',
  '',
  '7,804',
  ''],
 ['Haiti',

In [22]:
!pip install pandas
!pip install matplotlib
!pip install seaborn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /home/rb/.local/lib/python3.10/site-packages (1.5.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /home/rb/.local/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.21.0 in /home/rb/.local/lib/python3.10/site-packages (from pandas) (1.23.4)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas) (2022.2.1)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in /home/rb/.local/lib/python3.10/site-packages (3.6.2)
Requirement already satisfied: python-dateutil>=2.7 in /home/rb/.local/lib/python3.10/site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: numpy>=1.19 in /home/rb/.local/lib/python3.10/site-packages (from matplotlib) (1.23.4)
Requirement already satisfied: pillow>=6.2.0 in /usr/lib/python3/dist-packages (from matplotlib) (9.2.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/rb/.local/lib/python3.10/site-packages (from matplotlib) (4.38.0)
Requirement already satisfied: packaging>=20.0 in /home/rb/.local/lib/python3.10/site-packages (from matplotlib) (21.3)
Requirement already satisfied: cycler>=0.10 in /home/rb/.local/lib/python3.10/site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: contourpy>=1.0.1 in /home/rb/.local/lib/python3.10/site-packages (from matplotlib) (1.0.6)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/lib/python3/dist-packages (from matplotlib) (3.0.7)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/rb/.local/lib/python3.10/site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: seaborn in /home/rb/.local/lib/python3.10/site-packages (0.12.1)
Requirement already satisfied: pandas>=0.25 in /home/rb/.local/lib/python3.10/site-packages (from seaborn) (1.5.1)
Requirement already satisfied: matplotlib!=3.6.1,>=3.1 in /home/rb/.local/lib/python3.10/site-packages (from seaborn) (3.6.2)
Requirement already satisfied: numpy>=1.17 in /home/rb/.local/lib/python3.10/site-packages (from seaborn) (1.23.4)
Requirement already satisfied: packaging>=20.0 in /home/rb/.local/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (21.3)
Requirement already satisfied: pillow>=6.2.0 in /usr/lib/python3/dist-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (9.2.0)
Requirement already satisfied: python-dateutil>=2.7 in /home/rb/.local/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/rb/.local/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.4.4)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/lib/python3/dist-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (3.0.7)
Requirement already satisfied: fonttools>=4.22.0 in /home/rb/.local/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (4.38.0)
Requirement already satisfied: cycler>=0.10 in /home/rb/.local/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (0.11.0)
Requirement already satisfied: contourpy>=1.0.1 in /home/rb/.local/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.0.6)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas>=0.25->seaborn) (2022.2.1)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.1->seaborn) (1.16.0)

In [23]:
import pandas as pd # as pd is alias name convention

In [24]:
df = pd.DataFrame(clean_data)

In [25]:
df

,0,1,2,3,4,5,6,7,8
0,USA,"100,962,660",,"1,107,794",,"98,374,922",,"1,479,944","3,495"
1,India,"44,674,874",,"530,633",,"44,138,805",,"5,436",698
2,France,"38,184,081",,"159,362",,"37,057,677",,"967,042",869
3,Germany,"36,649,979",,"158,559",,"35,986,500","+33,100","504,920","1,406"
4,Brazil,"35,482,252",,"690,465",,"34,262,104",,"529,683","8,318"
...,...,...,...,...,...,...,...,...,...
225,Niue,180,,,,114,,66,
226,Vatican City,29,,,,29,,0,
227,Western Sahara,10,,1,,9,,0,
228,MS Zaandam,9,,2,,7,,0,
229,China,"349,938","+4,409","5,235",,"301,748","+3,935","42,955",128

In [26]:
col_names = ['country', 
             'total cases',
             'new cases', 
             'total death', 
             'new death',
             'total reovered',
             'new recovered',
             'active cases',
            'critical']

In [27]:
# updating column names on pandas dataframe

In [28]:
df.columns = col_names #update column name from data frame

In [29]:
df.head() #print 5 data rows from the top

,country,total cases,new cases,total death,new death,total reovered,new recovered,active cases,critical
0,USA,"100,962,660",,"1,107,794",,"98,374,922",,"1,479,944","3,495"
1,India,"44,674,874",,"530,633",,"44,138,805",,"5,436",698
2,France,"38,184,081",,"159,362",,"37,057,677",,"967,042",869
3,Germany,"36,649,979",,"158,559",,"35,986,500","+33,100","504,920","1,406"
4,Brazil,"35,482,252",,"690,465",,"34,262,104",,"529,683","8,318"

In [30]:
df.tail() #last 5 data

,country,total cases,new cases,total death,new death,total reovered,new recovered,active cases,critical
225,Niue,180,,,,114,,66,
226,Vatican City,29,,,,29,,0,
227,Western Sahara,10,,1,,9,,0,
228,MS Zaandam,9,,2,,7,,0,
229,China,"349,938","+4,409","5,235",,"301,748","+3,935","42,955",128

#convert dataframe to csv

In [31]:
df.to_csv('covid-live_dec7.csv', index = False) #index = False -- dont save index

In [32]:
# Reading csv file in pandas

In [33]:
filename = 'covid-live_dec7.csv'
covid_data = pd.read_csv(filename)

In [34]:
covid_data.head()

,country,total cases,new cases,total death,new death,total reovered,new recovered,active cases,critical
0,USA,"100,962,660",NaN,"1,107,794",NaN,"98,374,922",NaN,"1,479,944","3,495"
1,India,"44,674,874",NaN,"530,633",NaN,"44,138,805",NaN,"5,436",698
2,France,"38,184,081",NaN,"159,362",NaN,"37,057,677",NaN,"967,042",869
3,Germany,"36,649,979",NaN,"158,559",NaN,"35,986,500","+33,100","504,920","1,406"
4,Brazil,"35,482,252",NaN,"690,465",NaN,"34,262,104",NaN,"529,683","8,318"

In [35]:
# Nan is a missing data

## Find no of missing value in each column

In [37]:
covid_data.isna()

,country,total cases,new cases,total death,new death,total reovered,new recovered,active cases,critical
0,False,False,True,False,True,False,True,False,False
1,False,False,True,False,True,False,True,False,False
2,False,False,True,False,True,False,True,False,False
3,False,False,True,False,True,False,False,False,False
4,False,False,True,False,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...
225,False,False,True,False,True,False,True,False,True
226,False,False,True,False,True,False,True,False,True
227,False,False,True,False,True,False,True,False,True
228,False,False,True,False,True,False,True,False,True
229,False,False,False,False,True,False,False,False,False

In [38]:
 covid_data.isna().sum()

country             0
total cases         0
new cases         225
total death         0
new death         227
total reovered     20
new recovered     217
active cases       19
critical           91
dtype: int64